language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0

# Tests are ran against the repos early history
git:
  depth: 10000

bundler_args: --without darwin debug

notifications:
  email: false

before_script:
  # Tests requires the master branch to be present
  - git remote add origin-for-master https://github.com/kevinjalbert/git_statistics
  - git fetch origin-for-master
  - git checkout master
  - git checkout -

script: bundle exec rspec

before_install:
   - gem update --system
   - gem install bundler
