language: ruby

rvm:
  - 1.9.2
  - 1.9.3

bundler_args: --without test darwin

before_install:
  - sudo apt-get update --quiet
  - sudo apt-get install libicu-dev --quiet

notifications:
  email: false
