language: ruby

rvm:
  - 1.9.2
  - 1.9.3

bundler_args: --without test darwin

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libicu-dev

notifications:
  email: false

script: bundle exec rspec spec --tag ~@skip_travis
