language: ruby

rvm:
  - 1.9.2
  - 1.9.3

bundler_args: --without test darwin

before_install:
  - sudo apt-get --quiet update
  - sudo apt-get --quiet install libicu-dev

notifications:
  email: false
